version: "3"
services:
  switchhost:
    stdin_open: true
    tty: true
    build:
      context: .
    ports:
      - 8080:8080
      - 2121:2121
    volumes:
      - ./:/switchhost/src/:Z
      - ./config.json:/data/config.json
      - ~/.switch/prod.keys:/data/prod.keys