version: "3"
services:
  switchhost:
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - ./:/switchhost/src/:Z
      - ./config.json:/data/config.json
      - ~/.switch/prod.keys:/data/prod.keys